{
    'name': 'EGP HR ORG-Structure',
    'version': '17.1.0',
    'summary': 'EGP HR ORG-Structure module streamlines HR ORG-Structure processes',
    'description': 'MCIT-Afghanistan EGP HR',
    'category': 'Custom',
    'sequence': -3,
    'author': 'Javed Ahmadzai',
    'website': 'https://mcit.gov.af/',
    'depends': ['hr', 'mail', 'base', 'hr_gamification', 'hr_recruitment', 'hr_recruitment_skills', 'egp_hr_recruitment'],
    'data': [
        'security/egp_hr_org_structure_groups.xml',
        'security/ir.model.access.csv',
        'security/egp_hr_org_structure_security.xml',
        'data/egp_hr_structure_sequence.xml',
        'data/egp_hr_org_structure_res_partner_default_data.xml',
        'data/egp_hr_org_structure_work_location_default_data.xml',
        'data/egp_hr_org_structure_contract_type_default_data.xml',
        'data/egp_hr_org_structure_users_default_data.xml',
        # 'data/egp_hr_org_structure_department_default_data.xml',
        # 'data/egp_hr_org_structure_job_default_data.xml',
        'views/egp_hr_org_structure_department_view.xml',
        'views/egp_hr_org_structure_job_view.xml',
        'views/egp_hr_org_structure_work_location_view.xml',
        'views/egp_hr_org_structure_tashkil_view.xml',
        'views/egp_hr_resume_line_form_inherited.xml',
        'report/egp_hr_org_structure_job_summary_paper_format.xml',
        'report/egp_hr_org_structure_job_summary_template.xml',
        'report/egp_hr_org_structure_job_description_template.xml',
        'report/egp_hr_org_structure_tashkil_report_template_copy.xml',
        'wizard/egp_hr_org_structure_tashkil_wizard_report_form_view.xml',
        'report/egp_hr_org_structure_tashkil_wizard_report_template.xml',
        'report/egp_hr_structure_report_action.xml',
    ],
    'demo': [
    ],
    'images': ['static/description/icon.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
